# Cloud Build configuration for automated deployment
steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/travelsnap:latest', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/travelsnap:latest']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'travelsnap'
      - '--image'
      - 'gcr.io/$PROJECT_ID/travelsnap:latest'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--timeout'
      - '300'
      - '--set-env-vars'
      - 'REPLICATE_API_TOKEN=${_REPLICATE_API_TOKEN},SERPAPI_API_KEY=${_SERPAPI_API_KEY},GEMINI_API_KEY=${_GEMINI_API_KEY}'

images:
  - 'gcr.io/$PROJECT_ID/travelsnap:latest'

options:
  machineType: 'N1_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
